-- Удаление таблиц для тестирования в постмане.
drop table if exists comments cascade ;
drop table if exists bookings cascade;
drop table if exists requests cascade;
drop table if exists items cascade;
drop index if exists idx_user_email;
drop table if exists users cascade;

-- Пользователь
create table if not exists users (
    user_id bigint generated by default as identity,
    user_name varchar(255) not null,
    user_email varchar(255) not null,
    constraint pk_user_id primary key (user_id),
    constraint uq_user_email unique (user_email)
);

create index if not exists idx_user_email on users (user_email);

-- Запросы вещей
create table if not exists requests (
    request_id bigint generated by default as identity,
    request_description varchar(255) not null,
    user_id bigint,
    request_created timestamp without time zone not null,
    constraint pk_request_id primary key (request_id),
    constraint fk_request_user foreign key (user_id) references users(user_id) on delete cascade
);

-- Вещь
create table if not exists items (
    item_id bigint generated by default as identity,
    item_name varchar(255) not null,
    item_description varchar(1024) not null,
    item_is_available boolean not null,
    user_id bigint,
    request_id bigint,
    constraint pk_item_id primary key (item_id),
    constraint fk_item_owner_user foreign key (user_id) references users(user_id) on delete cascade,
    constraint fk_item_request foreign key (request_id) references requests(request_id) on delete set null
);

-- Бронирование вещи
create table if not exists bookings (
    booking_id bigint generated by default as identity,
    booking_startdt timestamp without time zone not null,
    booking_enddt timestamp without time zone not null,
    item_id bigint,
    user_id bigint,
    booking_status varchar(10),
    constraint pk_booking_id primary key (booking_id),
    constraint fk_booking_booker_user foreign key (user_id) references users(user_id) on delete cascade,
    constraint fk_booking_item foreign key (item_id) references items(item_id) on delete cascade
);

-- Отзывы
create table if not exists comments (
    comment_id bigint generated by default as identity,
    comment_text varchar(1024) not null,
    item_id bigint,
    user_id bigint,
    comment_created timestamp without time zone not null,
    constraint pk_comment_id primary key (comment_id),
    constraint fk_comment_author_user foreign key (user_id) references users(user_id) on delete cascade,
    constraint fk_comment_item foreign key (item_id) references items(item_id) on delete cascade
);